##配置邮件发送参数
##以163邮箱为例
spring:
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtp
    username: dhuzmiao@163.com
    password: RUFYAETRFIVHCFPF
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          port: 465
          starttls:
            enable: true
            required: true